<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>


<p><span style="font-family: tahoma, arial, helvetica, sans-serif;">Contact opnemen met Vinopio</span></p>
<p><span style="font-family: tahoma, arial, helvetica, sans-serif;">Contact met de klantenservice van Vinopio.be Heb je een vraag, opmerking of wil je advies? Kijk eerst even bij de <a href="vragen">veelgestelde vragen!</a></span><br /><span style="font-family: tahoma, arial, helvetica, sans-serif;">Als het antwoord er niet bij staat, neem dan contact op met klantenservice van Vinopio : info@vinopio.be</span>&nbsp;</p>
<address>Vinopio,&nbsp;Zwartven 16,&nbsp;2910 Essen</address><address>E mail: info@vinopio.be |&nbsp;Telefoon + 32 485 759070 |&nbsp;BTW nr BE 0843 766 178</address>
<div class="page-title">
    <h1>Mail ons</h1>
</div>

<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label">
            <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
        </div>
        <ul>
       <li class="first-list">
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name"
                       id="name"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        </li>
        <li class="2nd-list">
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone"
                       id="telephone"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                       class="input-text"
                       type="tel" />
            </div>
        </div>
        </li>
        <li class="third-list">
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment"
                          id="comment"
                          title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"
                ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        </li>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

<p class="bottom-contact"><span style="font-family: tahoma, arial, helvetica, sans-serif;">De klantenserice is bereikbaar op maandag tot met vrijdag van 10.00 tot 16.00 uur, woensdag van 10.00 tot 12.00 uur. Wij zullen je vraag of klacht zo spoedig mogelijk in behandeling nemen. U kunt op werkdagen van ons binnen 48 uur een antwoord verwachten. Je kunt ook een klacht voorleggen aan de geschillencommisie via het Europese ORD Platform:<a class="textlink" href="http://ec.europa.eu/consumers/odr/" target="_blank">http://ec.europa.eu/consumers/odr/</a>.</span></p>
<p><span style="font-family: tahoma, arial, helvetica, sans-serif;">Omdat we streven naar volledige tevredenheid van ons service, zullen we je aanvraag binnen de 5 werkdagen proberen op te lossen. Wilt je ons complimenteren of een suggestie? Laat het ons dan weten, we stellen je reactie zeer op prijs.</span></p>
<p><span style="font-family: tahoma, arial, helvetica, sans-serif;">Vinopio beschikt over een drank vergunning ingevolge drank-en horecawet.</span></p>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
