<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>

<?php
$category = $block->getCurrentCategory();
$parent_category_id = $category->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
 $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');// Instance of Category Model
 $categoryId =$category->getId(); // YOUR CATEGORY ID
 $category = $categoryFactory->create()->load($categoryId);
 // Parent Categories
 $parentCategories = $category->getParentCategories();
// Children  Categories
$childrenCategories = $category->getChildrenCategories();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
if ($childrenCategories->count() != 0):
?>
<div class="landing-categories">
		        <?php
		         foreach ($childrenCategories as $cat){
		             ?>
		             <?php
                        $category = $objectManager->create('Magento\Catalog\Model\Category')->load($cat->getId());
                        $_outputhelper    = $this->helper('Magento\Catalog\Helper\Output');
                        $_imgHtml   = '';
                        if ($_imgUrl = $category->getImageUrl()) {
                            $_imgHtml = '<img src="' .$baseUrl.'pub'. $_imgUrl . '" />';
                            $_imgHtml = $_outputhelper->categoryAttribute($category, $_imgHtml, 'image');
                            /* @escapeNotVerified */ 
                        }
                    ?>
		             <div class="landing-category">
						<a href="<?php echo $cat->getUrl(); ?>">
								<?php echo $_imgHtml;?>
														<div class="title">
								<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><?php echo $cat->getName(); ?></font></font></h2>
								<span class="count"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">(<?php echo $cat->getProductCount(); ?> items)</font></font></span>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
                     <?php
                 }
		        ?>
	</div>
    <?php if ($_description = $block->getCurrentCategory()->getDescription()) :?>
        <div class="category-description">
            <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
                $block->getCurrentCategory(),
                $_description,
                'description'
            ) ?>
        </div>
    <?php endif; ?>

    <style>
    .landing-categories {
        width: 100%;
        float: left;
    } 
    .landing-category a {
        display: block;
        width: 22%;
        margin: 0 1% 1% 0;
        float: left;
        border: 1px solid #E2E2E2;
        padding: 10px;
        position: relative;
        height: 155px;
        background: #fff;
    }
    </style>
<?php else: ?>
    <style>
    .category-image .image{
        display: none;
    }
    </style>
<?php endif; ?>