<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Grouped Options for Magento 2
*/
?>
<?php /** @var \Amasty\GroupedOptions\Block\Adminhtml\Group\Edit\After $block */?>
<script>
    require([
        'Amasty_GroupedOptions/js/group-visual'
    ], function(Visual) {
        Visual(<?= /* @noEscape */ $block->getJsonVisualConfig() ?>);
    });
</script>
