<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\OpenGraphTags\ViewModel\ProductOgMarkup $viewModel
 */

$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
$priceAmount = $viewModel->getPriceAmount($product);
$title = $viewModel->getOpenGraphTitle($product);
$description = $viewModel->getOpenGraphDescription($product);
$productImageUrl = $viewModel->getImageUrl($product);
?>

<meta property="og:type" content="product"/>

<?php if ($title):?>
    <meta property="og:title" content="<?= $escaper->escapeHtml($title); ?>"/>
<?php endif;?>

<?php if ($description):?>
    <meta property="og:description" content="<?= $escaper->escapeHtml($description); ?>"/>
<?php endif;?>

<meta property="og:url" content="<?= $escaper->escapeUrl($product->getProductUrl()); ?>"/>

<?php if ($productImageUrl):?>
    <meta property="og:image" content="<?= $escaper->escapeUrl($productImageUrl); ?>"/>
<?php endif;?>

<meta property="og:site_name" content="<?= $escaper->escapeHtml($product->getStore()->getName()); ?>"/>

<?php if ($priceAmount):?>
    <meta property="product:price:amount" content="<?= $escaper->escapeHtml($priceAmount); ?>"/>
    <meta property="product:price:currency" content="<?= $escaper->escapeHtml($viewModel->getCurrency($product)); ?>"/>
<?php endif;?>
