<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\OpenGraphTags\ViewModel\CategoryOgMarkup $viewModel
 */

$viewModel = $block->getViewModel();
$category = $viewModel->getCurrentCategory();
$title = $viewModel->getOpenGraphTitle($category);
$description = $viewModel->getOpenGraphDescription($category);
$categoryImageUrl = $viewModel->getCategoryImageUrl($category);
?>

<meta property="og:type" content="category"/>

<?php if ($title):?>
    <meta property="og:title" content="<?= $escaper->escapeHtml($title); ?>"/>
<?php endif;?>

<?php if ($description):?>
    <meta property="og:description" content="<?= $escaper->escapeHtml($description); ?>"/>
<?php endif;?>

<meta property="og:url" content="<?= $escaper->escapeUrl($category->getUrl()); ?>"/>

<?php if ($categoryImageUrl):?>
    <meta property="og:image" content="<?= $escaper->escapeUrl($categoryImageUrl); ?>"/>
<?php endif;?>

<meta property="og:site_name" content="<?= $escaper->escapeHtml($category->getStore()->getName()); ?>"/>
