<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Ajax
 */
?>
<?php if ($block->isAjaxEnabled()): ?>
    <script type="text/x-magento-init"><?= \Zend_Json::encode($block->getJsonConfig()) ?></script>
<?php endif ?>
<script>
    window.mstNavAjax = <?=$block->isAjaxEnabled() ? 'true' : 'false'?>;

    window.mstInstantlyMode = <?=$block->isInstantMode() ? 'true' : 'false'?>;
    window.mstNavConfirmationMode = <?=$block->isConfirmationMode() ? 'true' : 'false'?>;
    window.mstSeoFilterEnabled = <?=$block->isSeoFilterEnabled() ? 'true' : 'false'?>;
    window.mstHighlightEnabled = <?=$block->isHighlightEnabled() ? 'true' : 'false'?>;
    window.mstFriendlyClearUrl = '<?=$block->getFriendlyClearUrl()?>';
</script>

<script>
    function handleFiltersNavPositions() {
        var filtersConfig = <?= json_encode($block->getFiltersNavPositions()) ?>;

        document.querySelectorAll('.sidebar [data-mst-nav-filter]').forEach(function (filterOptions) {
            var attributeCode = filterOptions.getAttribute('data-mst-nav-filter').replace(/A\d{6}A/, '');

            if (filtersConfig.hasOwnProperty(attributeCode)) {
                filterOptions.closest('.filter-options-item').setAttribute('data-nav-position', filtersConfig[attributeCode]);
            }
        }.bind(this))
    }

    document.addEventListener('DOMContentLoaded', handleFiltersNavPositions);
</script>

<script type="text/x-magento-init"><?= \Zend_Json::encode([
        '*' => [
            'Mirasvit_LayeredNavigation/js/theme-compatibility' => [],
        ],
    ]) ?></script>

<script>
    require(
        ['jquery'],
        function($) {
            $(document).ready(function () {
                $('.catalogsearch-result-index #m-navigation-replacer').replaceWith($('.mst-nav__horizontal-bar'));
            });
        }
    );
</script>
